{
    name: "Barley",
   	category: "Grains Category",
    	price: 60,
    	user: req.user._id,
    	image: "/images/barley.jpg",
    	description: "provided per kg",
},
{
    name: "Bread",
   	category: "Breakfast Category",
    	price: 40,
    	user: req.user._id,
    	image: "/images/bread.jpg",
    	description: "provided per package",
},
{
    name: "Chicken Meat",
   	category: "Meat Category",
    	price: 500,
    	user: req.user._id,
    	image: "/images/chicken.jpg",
    	description: "provided per kg",
},
{
    name: "Fish",
   	category: "Meat Category",
    	price: 100,
    	user: req.user._id,
    	image: "/images/fish.jpg",
    	description: "provided per kg",
},
{
    name: "Pickles",
   	category: "Dairy Category",
    	price: 500,
    	user: req.user._id,
    	image: "/images/pickles.jpg",
    	description: "provided per kg",
},
{
    name: "Rice",
   	category: "Grains Category",
    	price: 100,
    	user: req.user._id,
    	image: "/images/rice.jpg",
    	description: "provided per kg",
},
{
    name: "School Lunch",
   	category: "Grains Category",
    	price: 100,
    	user: req.user._id,
    	image: "/images/schoollunch.jpg",
    	description: "provided per lunch",
},